stages:
  - build

build:
  stage: build
  image: gcr.io/kaniko-project/executor:latest
  script:
    - echo "Project ID - ${CI_PROJECT_ID}"
    - echo "Commit SHA - ${CI_COMMIT_SHA}"

    - echo "Identifying affected apps by this commit..."
    - APPS_CHANGED=$(find apps -type d -mindepth 1 -maxdepth 1 -exec basename {} \;)

    - IMAGE_TAG="${CI_COMMIT_SHA:0:8}-${CI_MERGE_REQUEST_IID}"
    - echo "Using image tag - $IMAGE_TAG"

    - |
      if [ -n "$APPS_CHANGED" ]; then
        echo "Changed apps: $APPS_CHANGED";
        for app in $APPS_CHANGED; do
          if [ -f "${CI_PROJECT_DIR}/Dockerfile.prod" ]; then
            echo "Building image for $app";
            /kaniko/executor --context "${CI_PROJECT_DIR}" \
              --dockerfile "${CI_PROJECT_DIR}/Dockerfile.prod" \
              --build-arg APP_NAME="$app" \
              --destination "http://10.110.255.103:5000/barnie/$app:$IMAGE_TAG" \
              --insecure \
              --skip-tls-verify \
              --build-arg HARBOR_USERNAME="$HARBOR_USERNAME" \
              --build-arg HARBOR_PASSWORD="$HARBOR_PASSWORD";

            echo "Image pushed to Harbor registry for $app";
          else
            echo "Skipping $app - Dockerfile.prod not found";
          fi
        done;
      else
        echo "No affected apps found.";
      fi
