build_apps:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ''
  script:
    - echo '{"insecure-registries":["http://harbor-registry.devops:5000"]}' > /etc/docker/daemon.json
    - dockerd &
    - sleep 10
    - docker login -u "admin" -p "Harbor12345" http://harbor-registry.devops:5000
  only:
    - develop
