stages:
  - build

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  variables:
    CONTAINER_NAME: momomo
    CONTAINER_TAG: 1.0.0
  before_script:
    - apk add --no-cache git
  script:
    - echo "Project ID - ${CI_PROJECT_ID}"
    - echo "Merge Request IID - ${CI_MERGE_REQUEST_IID}"

    # Ensure we have a full clone
    - git fetch --unshallow || echo "Already a full clone"

    # Identify affected apps by this commit
    - echo "Identifying affected apps by this commit..."
    - APPS_CHANGED=$(git diff --name-only origin/main...$CI_COMMIT_SHA | grep '^apps/' | cut -d'/' -f2 | sort -u)

    # Loop through affected apps and build them
    - |
      if [ -n "$APPS_CHANGED" ]; then
        echo "Changed apps: $APPS_CHANGED";
        for app in $APPS_CHANGED; do
          echo "Building image for $app";
          /kaniko/executor --context "${CI_PROJECT_DIR}/apps/$app" --dockerfile "${CI_PROJECT_DIR}/apps/$app/Dockerfile.prod" --destination $CONTAINER_REGISTRY/$app:$CONTAINER_TAG;
        done;
      else
        echo "No affected apps found.";
      fi
  tags:
    - kaniko
