stages:
  - build

# https://docs.gitlab.com/ee/ci/docker/using_kaniko.html
build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  variables:
    CONTAINER_REGISTRY: $CI_REGISTRY
  script:
    - echo "Identifying afected apps by this commit..."
    - APPS_CHANGED=$(git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA | grep -oP '^apps/\K[^/]*' | sort -u)
    
    # Check if any app has been affected by this commit:
    - |
      if [ -z "$APPS_CHANGED" ]; then
        echo "No hay aplicaciones afectadas en este commit. Saliendo..."
        exit 0
      fi

    # Build and register apps images:
    - for app in $APPS_CHANGED; do
        echo "Building image for app: $app";
        /kaniko/executor \
          --context "${CI_PROJECT_DIR}/apps/$app" \
          --dockerfile "${CI_PROJECT_DIR}/Dockerfile.prod" \
          --destination "$CONTAINER_REGISTRY/$CI_PROJECT_PATH/$app:${CI_COMMIT_SHA}" \
          --build-arg APP_NAME=$app;
      done
  only:
    - merge_requests
  tags:
    - kaniko
