stages:
  - build

build:
  stage: build
  image: docker:20.10.7-dind
  services:
    - name: docker:20.10.7-dind
  before_script:
    - echo '{"insecure-registries":["10.110.255.103:5000"]}' > /etc/docker/daemon.json
    - systemctl restart docker
  script:
    - echo "Project ID - ${CI_PROJECT_ID}"
    - echo "Commit SHA - ${CI_COMMIT_SHA}"

    - echo "Identifying affected apps by this commit..."
    - APPS_CHANGED=$(find apps -type d -mindepth 1 -maxdepth 1 -exec basename {} \;)

    - IMAGE_TAG="${CI_COMMIT_SHA:0:8}-${CI_MERGE_REQUEST_IID}"
    - echo "Using image tag - $IMAGE_TAG"

    - echo "$HARBOR_PASSWORD" | docker login 10.110.255.103:5000 -u "robot\$barnie+gitlab" --password-stdin

    - |
      if [ -n "$APPS_CHANGED" ]; then
        echo "Changed apps: $APPS_CHANGED";
        for app in $APPS_CHANGED; do
          if [ -f "${CI_PROJECT_DIR}/Dockerfile.prod" ]; then
            echo "Building image for $app";
            docker build -t "10.110.255.103:5000/barnie/$app:$IMAGE_TAG" -f "${CI_PROJECT_DIR}/Dockerfile.prod" .
            docker push "10.110.255.103:5000/barnie/$app:$IMAGE_TAG"

            echo "Image pushed to Harbor registry for $app";
          else
            echo "Skipping $app - Dockerfile.prod not found";
          fi
        done;
      else
        echo "No affected apps found.";
      fi
