stages:
  - build

# https://docs.gitlab.com/ee/ci/docker/using_kaniko.html
build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  variables:
    CONTAINER_NAME: momomo
    CONTAINER_TAG: 1.0.0
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination $CONTAINER_REGISTRY/$CONTAINER_NAME:$CONTAINER_TAG:latest"
  when: manual
  tags:
    - kaniko
