build_apps:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ''
  script:
    - dockerd --insecure-registry harbor-registry.devops:5000 &
    - sleep 10
    - docker info | grep -i insecure
    - docker login -u "admin" -p "Harbor12345" http://harbor-registry.devops:5000
  only:
    - develop
