# CI_REGISTRY_PASSWORD must be define as a variable in GitLab CI/CD settings: "$CI_REGISTRY_PASSWORD"
stages:
  - build

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  script:
    - echo "Project ID - ${CI_PROJECT_ID}"
    - echo "Commit SHA - ${CI_COMMIT_SHA}"

    - echo "Identifying affected apps by this commit..."
    - APPS_CHANGED=$(find apps -type d -mindepth 1 -maxdepth 1 -exec basename {} \;)

    - IMAGE_TAG="${CI_COMMIT_SHA:0:8}-${CI_MERGE_REQUEST_IID}"
    - echo "Using image tag - $IMAGE_TAG"

    - |
      if [ -n "$APPS_CHANGED" ]; then
        echo "Changed apps: $APPS_CHANGED";
        for app in $APPS_CHANGED; do
          if [ -f "${CI_PROJECT_DIR}/Dockerfile.prod" ]; then
            echo "Building image for $app";
            /kaniko/executor --context "${CI_PROJECT_DIR}" \
              --dockerfile "${CI_PROJECT_DIR}/Dockerfile.prod" \
              --build-arg APP_NAME="$app" \
              --tarPath "/tmp/${app}-${IMAGE_TAG}.tar";
            
            echo "Uploading image to GitLab Package Registry for $app";
            curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file "/tmp/${app}-${IMAGE_TAG}.tar" \
              "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/$app/$IMAGE_TAG/${app}-${IMAGE_TAG}.tar"
          else
            echo "Skipping $app - Dockerfile.prod not found";
          fi
        done;
      else
        echo "No affected apps found.";
      fi
