build_apps:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ''
    DOCKER_BUILDKIT: 1
  script:
    - docker login -u "admin" -p "Harbor12345" http://harbor-registry.devops:5000
  only:
    - develop
