build_apps:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ''
  script:
    - dockerd --insecure-registry harbor-registry.devops:5000 &
    - sleep 10
    - docker info | grep -i insecure
    - curl -v http://harbor-registry.devops:5000/v2/
    - docker login -u "robot$barnie+gitlab" -p "2LcEgDACCuEWBzrwNZFvag4Z4QLkTosq" http://harbor-registry.devops:5000
  only:
    - develop
