stages:
  - build

variables:
  DOCKER_REGISTRY: '$CI_REGISTRY'
  DOCKER_IMAGE: '$DOCKER_REGISTRY/<nombre_del_proyecto>'

build:
  stage: build
  script:
    - npm install
    - |
      for app in $(nx print-affected --type=app --select=projects); do
        echo "Building Docker image for $app"
        docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA -f Dockerfile --build-arg APP_NAME=$app .
        docker push $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA
      done
  only:
    - branches
