const enum ENDPOINTS {
  USERS = '/users',
  TOKENS = '/tokens',
  FORGOT_PASSWORD = '/forgot_password',
  VERIFY_USER = '/verify_user',
  REFRESH_TOKEN = '/refresh-token',
}

export enum PARAMS {
  USER_ID = 'user_id',
  FORGOT_PASSWORD_TOKEN = 'resetPasswordToken',
  VERIFY_USER_TOKEN = 'verificationToken',
}

export const ROUTES = {
  USERS: ENDPOINTS.USERS,
  VERIFY_USER: `${ENDPOINTS.VERIFY_USER}/:${PARAMS.VERIFY_USER_TOKEN}`,
  TOKENS: ENDPOINTS.TOKENS,
  REQUEST_FORGOT_PASSWORD: ENDPOINTS.FORGOT_PASSWORD,
  SET_PASSWORD: `${ENDPOINTS.FORGOT_PASSWORD}/:${PARAMS.FORGOT_PASSWORD_TOKEN}`,
  REFRESH_TOKEN: ENDPOINTS.REFRESH_TOKEN,
};
